/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view;

import static client.Main.addOrderPage;
import static client.Main.CLINIC_HEALTHCARE;
import static client.Main.DISTRIBUTION;
import static client.Main.MANUFACTURER;
import static client.Main.PATIENT;
import static client.Main.clinic_healthcare;
import static client.Main.current_user;
import static client.Main.manufacturerHomePage;
import static client.Main.patient_appointment_info;
import static client.Main.patient_view;
import static client.Main.userList;
import model.User;
import static client.Main.register;
import static client.Main.update_production_status;
import static client.Main.patient_info;
import static client.Main.patient_track;
import static client.Main.patient_vaccination_record;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import model.Patient;
import util.Hasher;

/**
 *
 * @author acer
 */
public class Login extends javax.swing.JFrame {

  /**
   * Creates new form Login
   */
  public Login() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    usernameTextField = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    loginButton = new javax.swing.JButton();
    registerLabel = new javax.swing.JLabel();
    passwordTextField = new javax.swing.JPasswordField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);

    jPanel1.setBackground(new java.awt.Color(51, 51, 51));

    jLabel2.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(102, 255, 204));
    jLabel2.setText("Login");

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(204, 255, 255));
    jLabel3.setText("Username: ");

    jLabel4.setBackground(new java.awt.Color(255, 255, 255));
    jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(204, 255, 255));
    jLabel4.setText("Password:");

    usernameTextField.setBackground(new java.awt.Color(204, 204, 255));
    usernameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userIcon.png"))); // NOI18N

    loginButton.setBackground(new java.awt.Color(204, 255, 204));
    loginButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    loginButton.setText("Login");
    loginButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        loginButtonActionPerformed(evt);
      }
    });

    registerLabel.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
    registerLabel.setForeground(new java.awt.Color(255, 204, 204));
    registerLabel.setText("*Switch to register");
    registerLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    registerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        registerLabelMousePressed(evt);
      }
    });

    passwordTextField.setBackground(new java.awt.Color(204, 204, 255));
    passwordTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(182, 182, 182)
            .addComponent(jLabel1))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(31, 31, 31)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel3)
                  .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(usernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                  .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(passwordTextField)))))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(134, 134, 134)
            .addComponent(registerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(40, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel3)
            .addGap(8, 8, 8)))
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(52, 52, 52)
            .addComponent(jLabel4))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(44, 44, 44)
            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(41, 41, 41)
        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(registerLabel)
        .addContainerGap(97, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void registerLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMousePressed
    register.setVisible(true);
    this.setVisible(false);
    resetLogin();
  }//GEN-LAST:event_registerLabelMousePressed

  private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
    if(!usernameTextField.getText().isEmpty() && !String.valueOf(passwordTextField.getPassword()).isEmpty()){
      if(isUserExist(usernameTextField.getText(), String.valueOf(passwordTextField.getPassword()))){
          JOptionPane.showMessageDialog(null, current_user.getUserName()+ ", login Success!!");
          pageDisplayAfterLogin();
          readAllUser();
          this.setVisible(false);
          resetLogin();
      }
      else{
        JOptionPane.showMessageDialog(null, "Wrong UserName or Password!!","Error",JOptionPane.ERROR_MESSAGE);
      };
    }
    else{
      JOptionPane.showMessageDialog(null, "Username or Password is empty","Error",JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_loginButtonActionPerformed

  public void readAllUser(){
    FileInputStream fileinput;
    try {
      fileinput = new FileInputStream("register.txt");
      Scanner fileRow = new Scanner(fileinput);
      while(fileRow.hasNext()){
       String[] split_name = fileRow.nextLine().split(" \\|\\| ");
       userList.put(split_name[0], split_name[1]);
      }
    } catch (FileNotFoundException ex) {}
  }
  
  public void pageDisplayAfterLogin(){
    if(CLINIC_HEALTHCARE.equals(current_user.getRole())){
        clinic_healthcare = new Clinic_Healthcare_UI();
        patient_vaccination_record = new Patient_Vaccination_Record();
        clinic_healthcare.configureOrderTable();
        clinic_healthcare.setVisible(true);
        addOrderPage = new Add_Order();
      }
    else if(PATIENT.equals(current_user.getRole())){
      getPatientRecord();
      System.out.println(patient_info);
      patient_view = new Patient_View();
      patient_view.configurePatientPage();
      patient_appointment_info = new Patient_Appointment_Info();
      patient_track = new Patient_Track();
      patient_view.setVisible(true);
    }
    else if(MANUFACTURER.equals(current_user.getRole())){
      manufacturerHomePage = new Manufacturer_HomePage();
      manufacturerHomePage.configureOrderTable();
      manufacturerHomePage.setVisible(true);
      update_production_status = new Update_Production_Status();
    }
    else if(DISTRIBUTION.equals(current_user.getRole())){
       
    }
  }
  
  public void getPatientRecord(){
    patient_info = new ArrayList();
    FileInputStream fileinput;
    try {
      fileinput = new FileInputStream("Patient_Info.txt");
      Scanner fileRow = new Scanner(fileinput);
      while(fileRow.hasNext()){
       Patient patient = new Patient();
       patient.setUserName(fileRow.nextLine());
       patient.setStatus(fileRow.nextLine());
       patient.setBatch_id(Integer.valueOf(fileRow.nextLine()));
       patient.setFullName(fileRow.nextLine());
       patient.setAge(fileRow.nextLine());
       patient.setGender(fileRow.nextLine());
       patient.setIc(fileRow.nextLine());
       patient.setContactNumber(fileRow.nextLine());
       patient.setAddress(fileRow.nextLine());
       fileRow.nextLine();
       patient_info.add(patient);
      }
      fileRow.close();
    } catch (FileNotFoundException ex) {}
  }
  
  public void resetLogin(){
    usernameTextField.setText("");
    passwordTextField.setText("");
  }
  
  public static boolean isUserExist(String userName, String password){
    boolean isUserExist = false;
    FileInputStream fileinput;
    try {
      fileinput = new FileInputStream("register.txt");
      Scanner fileRow = new Scanner(fileinput);
      while(fileRow.hasNext()){
       String[] split_name = fileRow.nextLine().split(" \\|\\| ");
       String hashPassword = Hasher.hash(password, "SHA-512");
       if(userName.equals(split_name[0]) && hashPassword.equals(split_name[2])){
         current_user = new User(split_name[0], split_name[2], split_name[1]);
         isUserExist = true;
         break;
       }
      }
    } catch (FileNotFoundException ex) {}
    return isUserExist;
  }
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Login().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton loginButton;
  private javax.swing.JPasswordField passwordTextField;
  private javax.swing.JLabel registerLabel;
  private javax.swing.JTextField usernameTextField;
  // End of variables declaration//GEN-END:variables
}
